---
- hosts: dcos_all
  remote_user: centos
  name: PLAYBOOK Install Docker
  become: true
  vars:
    version: "1.13"

  tasks:
  - name: Add key
    shell: sudo rpm --import "https://sks-keyservers.net/pks/lookup?op=get&search=0xee6d536cf7dc86e2d7d56f59a178ac6c6238f52e"
  - name: Add official Docker yum repository
    yum_repository:
      name: packages.docker.com_1.13_yum_repo_main_centos_7 
      file: docker
      description: Official Docker yum repo
      baseurl: https://packages.docker.com/{{version}}/yum/repo/main/centos/7
      enabled: yes

  - name: Enable OverlayFS
    lineinfile:
      path: /etc/modules-load.d/overlay.conf
      state: present
      create: yes
      line: 'overlay'

  - name: Load OverlayFS kernel module
    modprobe:
      name: overlay
      state: present

  - name: Create Docker service config directory
    file:
      path: /etc/systemd/system/docker.service.d
      state: directory
      mode: 0755

  - name: Configure Docker to use OverlayFS
    blockinfile:
      path: /etc/systemd/system/docker.service.d/override.conf
      state: present
      create: yes
      block: |
        [Service]
        ExecStart=
        ExecStart=/usr/bin/dockerd --storage-driver=overlay

  - name: Install Docker {{version}}
    yum:
      name: docker-engine, docker-engine-selinux
      state: present

  - name: Start and enable Docker
    systemd:
      name: docker
      state: started
      enabled: True
