---
- hosts: dcos_all
  remote_user: centos
  become: false
  vars:
    INTERFACE_NAME: eno1

  tasks:
#  - name: Distribute ip-detect script
#    copy:
#      src: ../files/ip-detect-aws
#      dest: /home/centos/genconf/ip-detect

  - name: Shutdown all dc/os services
    shell: "systemctl stop -- $(systemctl show -p Wants dcos.target | cut -d= -f2)"
  - name: Disable dc/os active services
    shell: "systemctl disable -- $(systemctl show -p Wants dcos.target | cut -d= -f2)"
  - name: Disable zookeeper
    service: name=dcos-exhibitor.service state=stopped  enabled=false
#  - name: Uninstall pkgpanda
#    shell: "/opt/mesosphere/bin/pkgpanda uninstall"
  - name: Stop running containers
    shell: docker stop $(docker ps -a -q)
    ignore_errors: true
  - name: Stop all docker processes
    shell: "docker stop $(docker ps -a -q)"
    ignore_errors: true
  - name: Remove all docker processes
    shell: "docker rm $(docker ps -a -q)"
    ignore_errors: true
  - name: Remove all docker images
    shell: "docker rmi $(docker images -a -q)"
    ignore_errors: true
  - name: Uninstall docker
    yum: name=docker-engine state=absent
  - name: Uninstall docker-selinux
    yum: name=docker-engine-selinux state=absent
  - name: Delete active containers
    shell: docker rm $(docker ps -a -q)
    ignore_errors: true
  - name: delete unnecessary directories
    file: path={{ item.path }} state=absent
    with_items:
    - { path : '/etc/systemd/system/dcos.target.wants' }
    - { path : '/var/lib/dcos/exhibitor/zookeeper' }
    - { path : '/var/lib/docker' }
    - { path : '/opt/mesosphere' }
    - { path : '/etc/mesosphere' }
    - { path : '/var/lib/mesos' }
    - { path : '/var/lib/dcos' }
    - { path : '/var/lib/zookeeper' }
    - { path : '/var/log/mesos' }
    - { path : '/var/lib/mesosphere' }
    - { path : '/run/dcos' }
    - { path : '/etc/profile.d/dcos.sh' }
    - { path : '/etc/systemd/journald.conf.d/dcos.conf' }
    - { path : '/etc/systemd/system/dcos-cfn-signal.service' }
    - { path : '/etc/systemd/system/dcos-download.service' }
    - { path : '/etc/systemd/system/dcos-link-env.service' }
    - { path : '/etc/systemd/system/dcos-setup.service' }
    - { path : '/etc/systemd/system/multi-user.target.wants/dcos-setup.service' }
    - { path : '/etc/systemd/system/multi-user.target.wants/dcos.target' }