---
- hosts: dcos_all
  remote_user: centos
  become: true

  tasks:

  - name: Add DCOS assumed components
    yum: name={{item.name}} state=latest
    with_items:
      - { name: 'tar'}
      - { name: 'xz'}
      - { name: 'unzip' }
      - { name: 'curl' }
      - { name: 'ipset' }
#      - { name: 'docker-python' }
#      - { name: 'docker-py' }      
      - { name: 'git' }
      - { name: 'ntp' }
      - { name: 'python34' }

